<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{710c49b1-6c28-4dfa-b3ee-ba840c2a49f8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Commissioning();
P_ControlBox();
P_CraneControl();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>