<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="TestProgram" Id="{abfc07e4-da28-4e34-a608-54d649b9fe4a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TestProgram

VAR
	bTestVariable : BOOL;
	fTestVariable : REAL;
	nTestVariable : INT;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TestProgram">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>